// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: transcode/transcode_service.proto

package transcode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a new transcode task.
type CreateTranscodeTaskRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserUuid         string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	VideoUuid        string                 `protobuf:"bytes,2,opt,name=video_uuid,json=videoUuid,proto3" json:"video_uuid,omitempty"`
	InputPath        string                 `protobuf:"bytes,3,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	TargetResolution string                 `protobuf:"bytes,4,opt,name=target_resolution,json=targetResolution,proto3" json:"target_resolution,omitempty"`
	TargetBitrate    string                 `protobuf:"bytes,5,opt,name=target_bitrate,json=targetBitrate,proto3" json:"target_bitrate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTranscodeTaskRequest) Reset() {
	*x = CreateTranscodeTaskRequest{}
	mi := &file_transcode_transcode_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTranscodeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTranscodeTaskRequest) ProtoMessage() {}

func (x *CreateTranscodeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_transcode_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTranscodeTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTranscodeTaskRequest) Descriptor() ([]byte, []int) {
	return file_transcode_transcode_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTranscodeTaskRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreateTranscodeTaskRequest) GetVideoUuid() string {
	if x != nil {
		return x.VideoUuid
	}
	return ""
}

func (x *CreateTranscodeTaskRequest) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *CreateTranscodeTaskRequest) GetTargetResolution() string {
	if x != nil {
		return x.TargetResolution
	}
	return ""
}

func (x *CreateTranscodeTaskRequest) GetTargetBitrate() string {
	if x != nil {
		return x.TargetBitrate
	}
	return ""
}

// Response for CreateTranscodeTask.
type CreateTranscodeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskUuid      string                 `protobuf:"bytes,2,opt,name=task_uuid,json=taskUuid,proto3" json:"task_uuid,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTranscodeTaskResponse) Reset() {
	*x = CreateTranscodeTaskResponse{}
	mi := &file_transcode_transcode_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTranscodeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTranscodeTaskResponse) ProtoMessage() {}

func (x *CreateTranscodeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_transcode_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTranscodeTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTranscodeTaskResponse) Descriptor() ([]byte, []int) {
	return file_transcode_transcode_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTranscodeTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTranscodeTaskResponse) GetTaskUuid() string {
	if x != nil {
		return x.TaskUuid
	}
	return ""
}

func (x *CreateTranscodeTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to query a transcode task.
type GetTranscodeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUuid      string                 `protobuf:"bytes,1,opt,name=task_uuid,json=taskUuid,proto3" json:"task_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscodeTaskRequest) Reset() {
	*x = GetTranscodeTaskRequest{}
	mi := &file_transcode_transcode_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscodeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscodeTaskRequest) ProtoMessage() {}

func (x *GetTranscodeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_transcode_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscodeTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTranscodeTaskRequest) Descriptor() ([]byte, []int) {
	return file_transcode_transcode_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTranscodeTaskRequest) GetTaskUuid() string {
	if x != nil {
		return x.TaskUuid
	}
	return ""
}

// Response containing task status.
type GetTranscodeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskUuid      string                 `protobuf:"bytes,2,opt,name=task_uuid,json=taskUuid,proto3" json:"task_uuid,omitempty"`
	VideoUuid     string                 `protobuf:"bytes,3,opt,name=video_uuid,json=videoUuid,proto3" json:"video_uuid,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	OutputPath    string                 `protobuf:"bytes,6,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscodeTaskResponse) Reset() {
	*x = GetTranscodeTaskResponse{}
	mi := &file_transcode_transcode_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscodeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscodeTaskResponse) ProtoMessage() {}

func (x *GetTranscodeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_transcode_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscodeTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTranscodeTaskResponse) Descriptor() ([]byte, []int) {
	return file_transcode_transcode_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTranscodeTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTranscodeTaskResponse) GetTaskUuid() string {
	if x != nil {
		return x.TaskUuid
	}
	return ""
}

func (x *GetTranscodeTaskResponse) GetVideoUuid() string {
	if x != nil {
		return x.VideoUuid
	}
	return ""
}

func (x *GetTranscodeTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTranscodeTaskResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetTranscodeTaskResponse) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *GetTranscodeTaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_transcode_transcode_service_proto protoreflect.FileDescriptor

const file_transcode_transcode_service_proto_rawDesc = "" +
	"\n" +
	"!transcode/transcode_service.proto\x12\ttranscode\"\xcb\x01\n" +
	"\x1aCreateTranscodeTaskRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x1d\n" +
	"\n" +
	"video_uuid\x18\x02 \x01(\tR\tvideoUuid\x12\x1d\n" +
	"\n" +
	"input_path\x18\x03 \x01(\tR\tinputPath\x12+\n" +
	"\x11target_resolution\x18\x04 \x01(\tR\x10targetResolution\x12%\n" +
	"\x0etarget_bitrate\x18\x05 \x01(\tR\rtargetBitrate\"n\n" +
	"\x1bCreateTranscodeTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\ttask_uuid\x18\x02 \x01(\tR\btaskUuid\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"6\n" +
	"\x17GetTranscodeTaskRequest\x12\x1b\n" +
	"\ttask_uuid\x18\x01 \x01(\tR\btaskUuid\"\xea\x01\n" +
	"\x18GetTranscodeTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\ttask_uuid\x18\x02 \x01(\tR\btaskUuid\x12\x1d\n" +
	"\n" +
	"video_uuid\x18\x03 \x01(\tR\tvideoUuid\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x05R\bprogress\x12\x1f\n" +
	"\voutput_path\x18\x06 \x01(\tR\n" +
	"outputPath\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage2\xd5\x01\n" +
	"\x10TranscodeService\x12d\n" +
	"\x13CreateTranscodeTask\x12%.transcode.CreateTranscodeTaskRequest\x1a&.transcode.CreateTranscodeTaskResponse\x12[\n" +
	"\x10GetTranscodeTask\x12\".transcode.GetTranscodeTaskRequest\x1a#.transcode.GetTranscodeTaskResponseB#Z!transcode-service/proto/transcodeb\x06proto3"

var (
	file_transcode_transcode_service_proto_rawDescOnce sync.Once
	file_transcode_transcode_service_proto_rawDescData []byte
)

func file_transcode_transcode_service_proto_rawDescGZIP() []byte {
	file_transcode_transcode_service_proto_rawDescOnce.Do(func() {
		file_transcode_transcode_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcode_transcode_service_proto_rawDesc), len(file_transcode_transcode_service_proto_rawDesc)))
	})
	return file_transcode_transcode_service_proto_rawDescData
}

var file_transcode_transcode_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transcode_transcode_service_proto_goTypes = []any{
	(*CreateTranscodeTaskRequest)(nil),  // 0: transcode.CreateTranscodeTaskRequest
	(*CreateTranscodeTaskResponse)(nil), // 1: transcode.CreateTranscodeTaskResponse
	(*GetTranscodeTaskRequest)(nil),     // 2: transcode.GetTranscodeTaskRequest
	(*GetTranscodeTaskResponse)(nil),    // 3: transcode.GetTranscodeTaskResponse
}
var file_transcode_transcode_service_proto_depIdxs = []int32{
	0, // 0: transcode.TranscodeService.CreateTranscodeTask:input_type -> transcode.CreateTranscodeTaskRequest
	2, // 1: transcode.TranscodeService.GetTranscodeTask:input_type -> transcode.GetTranscodeTaskRequest
	1, // 2: transcode.TranscodeService.CreateTranscodeTask:output_type -> transcode.CreateTranscodeTaskResponse
	3, // 3: transcode.TranscodeService.GetTranscodeTask:output_type -> transcode.GetTranscodeTaskResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transcode_transcode_service_proto_init() }
func file_transcode_transcode_service_proto_init() {
	if File_transcode_transcode_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcode_transcode_service_proto_rawDesc), len(file_transcode_transcode_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcode_transcode_service_proto_goTypes,
		DependencyIndexes: file_transcode_transcode_service_proto_depIdxs,
		MessageInfos:      file_transcode_transcode_service_proto_msgTypes,
	}.Build()
	File_transcode_transcode_service_proto = out.File
	file_transcode_transcode_service_proto_goTypes = nil
	file_transcode_transcode_service_proto_depIdxs = nil
}
